[connections.gsheets]
spreadsheet = "你的谷歌表格链接(URL)"
type = "service_account"
project_id = "json里的project_id"
private_key_id = "json里的private_key_id"
private_key = "json里的private_key"
client_email = "json里的client_email"
client_id = "json里的client_id"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "json里的client_x509_cert_url"